### ISSUE TITLE
tabular data/ noisy instances/ new datasets

### ISSUE THREAD

**Issue by nazaretl** [Kthyeon/FINE_official#1]
Hi,
thanks for sharing your implementation. I have some questions about it:

1.	Does it also work on tabular data?
2.	Is the code tailored to the datasets used in the paper or can one apply it to any data?
3.	Is it possible to identify the noisy instances (return the noisy IDs or the clean set)?

Thanks!

**Comment by Kthyeon** [comment]
Hi,
1. we've not tried FINE on tabular data, but in my thought, FINE also can be a competitive solution for neural networks trained with tabular data
2. FINE can be applied to any data
3. Sure, it is!!
Best,
Taehyeon

**Comment by nazaretl** [comment]
thank you!
